name: story_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  get: ^4.5.1
  fluttertoast: ^8.0.8
  readmore: ^2.1.0
  dio: ^4.0.4
  go_router: ^7.0.0
  get_it: ^7.6.7
  get_storage: ^2.1.1
  rxdart: ^0.27.7
  progress_state_button: "^1.0.4"
  floating_action_bubble: ^1.1.4
  image_picker: ^1.0.2
  cached_network_image: ^3.3.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  country_flags: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/img/
  fonts:
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster/Lobster-Regular.ttf   
